config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :events, only: %i[new create show index]
  resources :sessions, only: %i[new create destroy]
  get '/signup', to: 'users#new'
  get '/logout', to: 'sessions#destroy'
  get '/signin', to: 'sessions#new'
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attended_event.rb
class AttendedEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attended_events, dependent: :destroy
  has_many :users, through: :attended_events, source: :user

  scope :upcoming_date, -> { select { |event| event.date >= Time.zone.now } }
  scope :past_date, -> { select { |event| event.date < Time.zone.now } }

  def self.creator(event)
    User.where(id: event.user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attended_events, dependent: :destroy
  has_many :events, through: :attended_events, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :login_required

  def login_required
    unless logged_in?
      flash.now[:notice] = 'You are not logged in, please do so or signup'
      redirect_to new_session_path
    end
  end

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  def current_user
    if session[:user_id]
      @current_user = User.find_by_id(session[:user_id])
      @current_user || false
    else
      false
    end
  end
  helper_method :current_user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :login_required, only: %i[new create]
  def show
    @event = Event.find_by_id(params[:id])
    @owner = Event.creator(@event)
  end

  def index
    @events = Event.all
    @past_event = @events.past_date
    @upcoming_event = @events.upcoming_date
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(events_params)
    if @event.save
      flash.now[:notice] = 'Save successfully'
      redirect_to user_path(current_user.id)
    else
      redirect_to new_events_path
    end
  end

  private

  def events_params
    params.require(:event).permit(:name, :description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_name(params[:name])
    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    elsif flash[:alert] = 'Invalid name or username'
      @user = User.new(params)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  private

  def login(_user)
    session[:user_id] = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    if @user.save
      flash.now[:success] = 'User has been successfully added'
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    if @user
      @past_events = @user.events.past_date
      @upcoming_events = @user.events.upcoming_date
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1> Events Happening </h1>

<% @events.each do |event| %>
    <p> <%= link_to event.name, event_path(event) %> </p>
<% end %>

<h3> Upcoming events </h3>
    <% @upcoming_event.each do |event| %>
        <%= event.name %>
    <% end %>

<h3> Past events </h3>
    <% @past_event.each do |event| %>
        <%= event.name %>
    <% end %>

app/views/events/new.html.erb
<h1> New Event </h1>

<%= form_for @event do |f|%>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br><br>
    <%= f.label :Description %><br>
    <%= f.text_field :description %><br><br>
    <%= f.label :Date %><br>
    <%= f.text_field :date %> <br><br>
    <%= f.button %>
<% end %>

app/views/events/show.html.erb
<h1> <%= @event.name%> </h1>

<p> <%= @event.description %> </p>

<h4> Attendees </h4>

<% @event.users.each do |user| %>
    <p><%= user.name %></p>
<% end %>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  Hi, <%= current_user.name %>
  <%= link_to 'Logout', logout_path %> &nbsp &nbsp |
  <%= link_to 'New Event', new_event_path %> |
  <%= link_to 'Back to Events', root_path %>
<% else %>
  <%= link_to 'Login', new_session_path %> &nbsp &nbsp | &nbsp &nbsp 
  <%= link_to 'Signup', new_user_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |type,  msg| %>
    <p style="color: red"><%= msg %></p>
  <% end %>
    <%= render 'layouts/header' %>
    <%= flash.notice %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h2> Signup </h2>

<%= form_for @user do |form| %>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br><br>
    <%= form.label :username %><br>
    <%= form.text_area :username %><br><br>
    <%= form.submit %>
<% end %>

app/views/users/show.html.erb
<p> <h3><%= @user.name %>'s Events List</h3> </p>

<ul>
    <h4> Created Events</h4>
            <% @user.events.each do |event| %>
                <li>
                    <%= link_to event.name, event_path(event) %> <br
                </li>
            <% end %>


    <h4> Past Events </h4>
        <li>
            <% if @past_events %>
            <% @past_events.each do |event|%> 
                <p> <%= event.name %></p>
                <% end %>
            <% else %>
                <%= fail %>
            <% end %>
        </li>

    <h4> Upcoming Events </h4>
        <li> <% @upcoming_events.each do |event| %> </li>
                <p> <%= event.name %></p>
                <% end %>
</ul>
    <p> <%= link_to 'Back', root_path %></p>